apiVersion: v1
kind: Service
metadata:
  name: go-person-manager-service
spec:
  type: NodePort
  selector:
    app: go-person-manager
  ports:
    - port: 8080
      targetPort: 3000
      nodePort: 31000
